name: BTC Discord Radar

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  signal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run BTC Radar
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python signal_bot.py
